### ISSUE TITLE
Missing a unique "key" prop error in dev mode - on the root page 🐛 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#757]
### URL of the Page

(root)

### What happened?

In the dev mode, I get a warning message that children in a list do not have unique "key" props, in the `QuickDraft` component:

<details>

<summary>  Console:

`Warning: Each child in a list should have a unique "key" prop.`

</summary>

```
Check the render method of `QuickDraft`. See https://reactjs.org/link/warning-keys for more information.
    at QuickDraft (webpack-internal:///./app/modules/components/QuickDraft.tsx:62:25)
    at div
    at FullWidthMenu (webpack-internal:///./app/core/components/NavbarFullwidthMenu.tsx:49:26)
    at div
    at div
    at Navbar (webpack-internal:///./app/core/components/Navbar.tsx:44:26)
    at Home (webpack-internal:///./app/pages/index.tsx:62:23)
    at BlitzInnerRoot (webpack-internal:///./node_modules/next/dist/stdlib/blitz-app-root.js:103:20)
    at Suspense
    at LayoutLoader (webpack-internal:///./app/core/components/LayoutLoader.tsx:17:23)
    at div
    at div
    at RecoilRoot_INTERNAL (webpack-internal:///./node_modules/recoil/es/index.js:4373:3)
    at RecoilRoot (webpack-internal:///./node_modules/recoil/es/index.js:4539:5)
    at Layout (webpack-internal:///./app/core/layouts/Layout.tsx:36:20)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/stdlib/error-boundary.js:146:9)
    at App (webpack-internal:///./app/pages/_app.tsx:37:24)
    at Hydrate (webpack-internal:///./node_modules/react-query/es/hydration/react.js:28:23)
    at QueryClientProvider (webpack-internal:///./node_modules/react-query/es/react/QueryClientProvider.js:39:21)
    at BlitzProvider (webpack-internal:///./node_modules/next/dist/stdlib/blitz-app-root.js:23:26)
    at BlitzWrapper (webpack-internal:///./node_modules/next/dist/stdlib/blitz-app-root.js:153:25)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:821:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:978:25)
```

</details>

### Steps to reproduce

1. On local development environment, `npm run dev`
2. Open localhost
3. Open the console

### What browser(s) did you use?

Chrome

**Comment by nsunami** [comment]
I see that this warning is happening across different pages, and thus I'm breaking up this issue to other issues. 
This issue will be about the root page.
