### ISSUE TITLE
"Expectation Violation" error message due to `recoil` in dev mode 🐛 

### ISSUE THREAD

**Issue by nsunami** [libscie/ResearchEquals.com#758]
### URL of the Page

/dashboard

### What happened?

In the development mode, I keep getting the following error message:

```

Expectation Violation: Duplicate atom key "workspaceFirstName". This is a FATAL ERROR in
      production. But it is safe to ignore this warning if it occurred because of
      hot module replacement.


```

(Note: the message repeats for other atom keys. Full error in the details below)

<details>

```
Expectation Violation: Duplicate atom key "workspaceFirstName". This is a FATAL ERROR in
      production. But it is safe to ignore this warning if it occurred because of
      hot module replacement.
    at expectationViolation (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:558:19)
    at registerNode (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:665:9)
    at baseAtom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8209:16)
    at atom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8262:12)
    at eval (webpack-internal:///./app/core/utils/Atoms.tsx:23:76)
    at ./app/core/utils/Atoms.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:660:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./app/core/modals/settings.tsx:13:70)
    at ./app/core/modals/settings.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:616:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
Expectation Violation: Duplicate atom key "workspaceLastName". This is a FATAL ERROR in
      production. But it is safe to ignore this warning if it occurred because of
      hot module replacement.
    at expectationViolation (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:558:19)
    at registerNode (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:665:9)
    at baseAtom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8209:16)
    at atom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8262:12)
    at eval (webpack-internal:///./app/core/utils/Atoms.tsx:28:75)
    at ./app/core/utils/Atoms.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:660:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./app/core/modals/settings.tsx:13:70)
    at ./app/core/modals/settings.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:616:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
Expectation Violation: Duplicate atom key "workspaceBio". This is a FATAL ERROR in
      production. But it is safe to ignore this warning if it occurred because of
      hot module replacement.
    at expectationViolation (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:558:19)
    at registerNode (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:665:9)
    at baseAtom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8209:16)
    at atom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8262:12)
    at eval (webpack-internal:///./app/core/utils/Atoms.tsx:33:70)
    at ./app/core/utils/Atoms.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:660:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./app/core/modals/settings.tsx:13:70)
    at ./app/core/modals/settings.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:616:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
Expectation Violation: Duplicate atom key "workspacePronouns". This is a FATAL ERROR in
      production. But it is safe to ignore this warning if it occurred because of
      hot module replacement.
    at expectationViolation (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:558:19)
    at registerNode (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:665:9)
    at baseAtom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8209:16)
    at atom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8262:12)
    at eval (webpack-internal:///./app/core/utils/Atoms.tsx:38:75)
    at ./app/core/utils/Atoms.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:660:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./app/core/modals/settings.tsx:13:70)
    at ./app/core/modals/settings.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:616:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
Expectation Violation: Duplicate atom key "workspaceUrl". This is a FATAL ERROR in
      production. But it is safe to ignore this warning if it occurred because of
      hot module replacement.
    at expectationViolation (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:558:19)
    at registerNode (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:665:9)
    at baseAtom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8209:16)
    at atom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8262:12)
    at eval (webpack-internal:///./app/core/utils/Atoms.tsx:43:70)
    at ./app/core/utils/Atoms.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:660:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./app/core/modals/settings.tsx:13:70)
    at ./app/core/modals/settings.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:616:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
Expectation Violation: Duplicate atom key "settingsModal". This is a FATAL ERROR in
      production. But it is safe to ignore this warning if it occurred because of
      hot module replacement.
    at expectationViolation (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:558:19)
    at registerNode (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:665:9)
    at baseAtom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8209:16)
    at atom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8262:12)
    at eval (webpack-internal:///./app/core/utils/Atoms.tsx:48:71)
    at ./app/core/utils/Atoms.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:660:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./app/core/modals/settings.tsx:13:70)
    at ./app/core/modals/settings.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:616:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
Expectation Violation: Duplicate atom key "userDiscord". This is a FATAL ERROR in
      production. But it is safe to ignore this warning if it occurred because of
      hot module replacement.
    at expectationViolation (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:558:19)
    at registerNode (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:665:9)
    at baseAtom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8209:16)
    at atom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8262:12)
    at eval (webpack-internal:///./app/core/utils/Atoms.tsx:53:69)
    at ./app/core/utils/Atoms.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:660:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./app/core/modals/settings.tsx:13:70)
    at ./app/core/modals/settings.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:616:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
Expectation Violation: Duplicate atom key "emailNotifications". This is a FATAL ERROR in
      production. But it is safe to ignore this warning if it occurred because of
      hot module replacement.
    at expectationViolation (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:558:19)
    at registerNode (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:665:9)
    at baseAtom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8209:16)
    at atom (/Users/nami/git/ResearchEquals.com/node_modules/recoil/cjs/index.js:8262:12)
    at eval (webpack-internal:///./app/core/utils/Atoms.tsx:58:76)
    at ./app/core/utils/Atoms.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:660:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./app/core/modals/settings.tsx:13:70)
    at ./app/core/modals/settings.tsx (/Users/nami/git/ResearchEquals.com/.next/server/pages/dashboard.js:616:1)
    at __webpack_require__ (/Users/nami/git/ResearchEquals.com/.next/server/webpack-runtime.js:33:42)

```

</details>

It looks like this issue is a bug when using `recoil` and `NextJS`:

1. [StackOverflow Post](https://stackoverflow.com/questions/65506656/recoil-duplicate-atom-key-in-nextjs)
2. This [GitHub issue](https://github.com/facebookexperimental/Recoil/issues/733) on recoil proposes various workarounds. And a patch on recoil is being worked on [this PR](https://github.com/facebookexperimental/Recoil/pull/2020) 

### Steps to reproduce

1. `npm run dev`
2. Go to the dashboard
3. Check the server log

### Anything else?

I don't think we can do much here, and the best way is to wait for an update for recoil. But, I wanted to create an issue since the error message floods the terminal, and it's a bit obnoxious. 😅

**Comment by nsunami** [comment]
From recoil 0.7.6, we can suppress the warning by setting the environment variable `RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED=FALSE`.

But then, doing so will also suppress legitimate errors.

**Comment by nsunami** [comment]
Since setting `RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED=FALSE` in `.env.local` fixes this issue. I consider it fixed. I'm updating the Wiki to note this. 🖊️
