### ISSUE TITLE
🐛 publishing with many references causing an `undefined` error

### ISSUE THREAD

**Issue by chartgerink** [libscie/ResearchEquals.com#836]
### What happened?

Somebody reported that they are trying to publish a module but it failed. 

```
TypeError: Cannot read properties of undefined (reading 'map')
    at eval (webpack-internal:///./app/api/test.ts:87:35)
    at Array.map (<anonymous>)
    at handler (webpack-internal:///./app/api/test.ts:68:145)
    at async Object.apiResolver (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/api-utils.js:114:13)
    at async DevServer.handleApiRequest (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/next-server.js:763:9)
    at async Object.fn (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/next-server.js:654:37)
    at async Router.execute (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/router.js:206:32)
    at async DevServer.run (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/next-server.js:831:29)
    at async DevServer.handleRequest (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/next-server.js:295:20)
```

Debugging and fixing as this is a very specific issue - creating an issue to track the problem. I will try to document what the issue is so we can reference it as we make the publishing process more robust.

### Steps to reproduce

n/a

**Comment by chartgerink** [comment]
Aha it looks like the error is because there are **no** authors retrieved from CrossRef (would need to do some digging whether this is in our retrieval or in CrossRef itself)

```
{
      "id": 353,
...
      "prefix": "10.1007",
      "suffix": "978-981-10-1607-3",
...
      "authorsRaw": {},
      "referencesRaw": {},
      "authors": []
    },
```

Catching this should, I hope, fix the issue. Working on it now.

**Comment by chartgerink** [comment]
Found that this is an issue with the `citation_list.tsx` - not in the publishing process. Making a PR now.
